### ISSUE TITLE
Update RPMC to 1.18

### ISSUE THREAD

**Issue by nerdyjohnny** [OiivaeCommunity/ovicommunity#42]

**Comment by nerdyjohnny** [comment]
Waiting for more of the RPMC plugins to update

**Comment by nerdyjohnny** [comment]
Once the new docker set up is complete, team will go through the plugins to update them, install the new version, and work on migrating the world to a 1.18-gen world

**Comment by nerdyjohnny** [comment]
Working on update now

**Comment by nerdyjohnny** [comment]
Files are copied. Working with Matt are fixing perm issues.

**Comment by thematbrown** [comment]
Update: I was able to get everything copied over with the exception of the Towny plugin which was causing errors when starting up the server. I will be working to get that plugin working correctly.

**Comment by nerdyjohnny** [comment]
Need to designate the Towny areas

**Comment by nerdyjohnny** [comment]
Need to update the server to 1.18.2
