### ISSUE TITLE
Mob Grinder Chest

### ISSUE THREAD

**Issue by Skitily** [OiivaeCommunity/ovicommunity#50]
Mob grinder chest cant be opened Because of the barrier around it

**Comment by Skitily** [comment]
i did it right right guys hahaah right right guys r r gith

**Comment by nerdyjohnny** [comment]
Worldguard flags need adjusted to allow chest use

**Comment by nerdyjohnny** [comment]
World Guard has been adjusted and it appears that there might be a PaperMC bug where the hopper and chest turns into blocks are restart then coverts back. We are going to monitor as we are using experimental builds of PaperMC for now, but the original issue has been fixed.
