### ISSUE TITLE
Investigate Docker and Oracle VM

### ISSUE THREAD

**Issue by nerdyjohnny** [OiivaeCommunity/ovicommunity#53]
See if these resources will be beneficial to us.

**Comment by nerdyjohnny** [comment]
Oracle VM test in progress. Most post shows that the VM could disapper in 30-60 days on the free tier. We need to watch this and make periodic backups.

**Comment by nerdyjohnny** [comment]
Downgraded in triage. We are gonna monitor the VM while also watching to see if the switch to Docker has any help

**Comment by nerdyjohnny** [comment]
Downgraded to Low. Server seems to be maintaining well. Stress test to be done on Sunday and MJB is still investigating Docker

**Comment by thematbrown** [comment]
Was able to get minecraft running within Docker container. I'll be working throughout the day to figure out how to implement the plugins and world files

**Comment by thematbrown** [comment]
Was able to successfully transfer over world data. World loads while plugins are installed but further testing is needed to make sure everything is working correctly. I will be moving on to begin stress testing the server

**Comment by nerdyjohnny** [comment]
Docker install was successful. Matt is in the steps of finishing the move over and adding users to the new panel

**Comment by nerdyjohnny** [comment]
Install complete.
