### ISSUE TITLE
Player can't send message in Minecraft chat

### ISSUE THREAD

**Issue by NomiSky** [OiivaeCommunity/ovicommunity#59]
**Describe the bug**
Player can't send message in chat.
**To Reproduce**
Not sure if it can be reproduced. 

**Expected behavior**
"Cannot send chat message" should show up in chat.

**Screenshots**
https://imgur.com/gmai9cz

**Additional context**

**Comment by nerdyjohnny** [comment]
Will investigate tomorrow. If @thematbrown could look at the console before I can, he might be able to see the issue.

**Comment by nerdyjohnny** [comment]
Discord ticket 49

**Comment by nerdyjohnny** [comment]
High probability it is a perm issue with the player as others are able to use the chat

**Comment by thematbrown** [comment]
Will investigate issue today

**Comment by nerdyjohnny** [comment]
Nireite is the username and they are using Lunar Client

**Comment by thematbrown** [comment]
Checked the console and the time frame when the issue occurred is not in the logs. I spoke with the user and will try to replicate the issue to get more information.

**Comment by nerdyjohnny** [comment]
Permissions DB was deleted and regenerated as a precaution. Was unable to locate the player in the permission db. This might stem from an issue when the server was created so hopefully a fresh perm DB will help

**Comment by nerdyjohnny** [comment]
Still awaiting for user to message back. If no response by end of week, issue will be closed

**Comment by nerdyjohnny** [comment]
Due to inactivity of ticket, it is being closed. Will reopen if activity reoccurs.
