### ISSUE TITLE
Bedrock players unable to connect

### ISSUE THREAD

**Issue by nerdyjohnny** [OiivaeCommunity/ovicommunity#63]
Bedrock players are unable to connect after the move to docker. May be an issue with the network set up.

**Comment by thematbrown** [comment]
Looking into issue, looks like it might be something to do with the port mapping

**Comment by thematbrown** [comment]
Fixed the Geyser plugin, looks like the port was listening over TCP and not UDP. I made changes to the stack and will upload the new changes
